### ISSUE TITLE
Tutorial video

### ISSUE THREAD

**Issue by greentea6** [witch-team/RICE50xmodel#1]
Hi, 
I was wondering if there is a tutorial video or document to run RICE. Also, wondering if it is possible to add different coalitions? 
Thank you.

**Comment by JohannesEmm** [comment]
Hello,

unfortunately we don't have a video tutorial (yet) available.

Multiple coalitions are feasible, see in this file: https://github.com/witch-team/RICE50xmodel/blob/main/modules/cooperation_coalitions.gms
but you need to know about multidimensional sets and how to define htem in gams, you see some example in this file but will need to develop it yourself e.g., editing this file.

**Comment by greentea6** [comment]
Thank you!

**Comment by greentea6** [comment]
Hi,

I was wondering if we can assess the impacts of varying carbon taxes for different regions when running the coalition scenario in RICE50. For example, a carbon tax of USD 100 for EU and USD 20 for non-EU? If it is possible, would it be possible to show some pointers? Thank you for your support as always :)
