### ISSUE TITLE
Region-specific carbon tax

### ISSUE THREAD

**Issue by greentea6** [witch-team/RICE50xmodel#2]
Hi,

I was wondering if we can assess the impacts of varying carbon taxes for different regions when running the coalition scenario in RICE50. For example, a carbon tax of USD 100 for EU and USD 20 for non-EU? If it is possible, would it be possible to show some pointers? Thank you for your support as always :)

**Comment by JohannesEmm** [comment]
Hi,
just run the model with argument "--policy=ctax" to enable the carbon tax.
And to have the values you suggest add these three lines after line 302 in modules/core_policy.gms
`ctax(t,n) = 0;
ctax(t,n)$(year(t) ge %ctax_start% and not eu(n)) = 100 / 1e3;
ctax(t,n)$(year(t) ge %ctax_start% and eu(n)) = 100 / 1e3;
`
